//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupOnC2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GROUPONEntities1 : DbContext
    {
        public GROUPONEntities1()
            : base("name=GROUPONEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public DbSet<CHITIETSANPHAM> CHITIETSANPHAMs { get; set; }
        public DbSet<COMMENT> COMMENTs { get; set; }
        public DbSet<DONHANG> DONHANGs { get; set; }
        public DbSet<HINHTHUCTHANHTOAN> HINHTHUCTHANHTOANs { get; set; }
        public DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public DbSet<MULTIMEDIA> MULTIMEDIAs { get; set; }
        public DbSet<PAYPAL> PAYPALs { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public DbSet<THANHTOANTRUCTIEP> THANHTOANTRUCTIEPs { get; set; }
        public DbSet<THONGTINADMIN> THONGTINADMINs { get; set; }
        public DbSet<THONGTINDOANHNGHIEP> THONGTINDOANHNGHIEPs { get; set; }
        public DbSet<THONGTINMEMBER> THONGTINMEMBERs { get; set; }
        public DbSet<TINHTRANGDONHANG> TINHTRANGDONHANGs { get; set; }
        public DbSet<TRANGTHAITAIKHOAN> TRANGTHAITAIKHOANs { get; set; }
    }
}
