//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupOnC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTIMEDIA
    {
        public string MaMD { get; set; }
        public string MaCTSP { get; set; }
        public string Multimedia1 { get; set; }
    
        public virtual CHITIETSANPHAM CHITIETSANPHAM { get; set; }
    }
}
