//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupOnC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOANTRUCTIEP
    {
        public string MaHTTT { get; set; }
        public string TenNN { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
    
        public virtual HINHTHUCTHANHTOAN HINHTHUCTHANHTOAN { get; set; }
    }
}
