//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupOnC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
		GROUPONEntities1 db = new GROUPONEntities1();
        public string MaCM { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string MaSP { get; set; }
        public string MaTK { get; set; }
        public string Noidung { get; set; }
		private string _UserName;

		public string UserName
		{
			get { return db.LayUserNameTheoMaTK(MaTK); }
			set { _UserName = value; }
		}
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
