//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupOnC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public TAIKHOAN()
        {
            this.COMMENTs = new HashSet<COMMENT>();
            this.DONHANGs = new HashSet<DONHANG>();
        }

        public TAIKHOAN(string ma, string un, string pw, string e, string av, string matt, string dc, string sdt)
        {
            MaTK = ma;
            UserName = un;
            Password = pw;
            Email = e;
            Avatar = av;
            MaTT = matt;
            DiaChi = dc;
            SDT = sdt;
        }
    
        public string MaTK { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
        public string MaTT { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
    
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual THONGTINADMIN THONGTINADMIN { get; set; }
        public virtual THONGTINDOANHNGHIEP THONGTINDOANHNGHIEP { get; set; }
        public virtual THONGTINMEMBER THONGTINMEMBER { get; set; }
        public virtual TRANGTHAITAIKHOAN TRANGTHAITAIKHOAN { get; set; }
    }
}
