//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupOnC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINDOANHNGHIEP
    {
        public string MaTK { get; set; }
        public string Website { get; set; }
        public string TenDN { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
