//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupOnC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHAITAIKHOAN
    {
        public TRANGTHAITAIKHOAN()
        {
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public string MaTT { get; set; }
        public string TenTT { get; set; }
    
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
